### PR TITLE
Add Web/WASM Support

### PR DESCRIPTION
**Pull request by nicholas-maltbie**
Hey, I'm learning godot and found your repo awesome @DmitriySalnikov

I'm trying to setup gdexport for web and ran across your issue #19 and I have been able to build it locally by adding the PThresds flags to enable shared memory in the export. And updating the version of emsdk to `3.1.46` to be in line with v4.1.1-stable of godot's web export. Thought I should share how I got it to build and export locally on my machine.

I've testing building it with v4.1.1-stable of godot and was able to compile and run on my local machine. Checkout my web build branch to see an example - https://github.com/nicholas-maltbie/godot_debug_draw_3d/tree/nickmaltbie/web-build

image

Also, I only have had it work with chromium-based browsers (Edge in the photo), seems like there is a note about it in the [Export for Web](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html) pages on the docs.

> If you use Linux, due to [poor Firefox WebGL performance](https://bugzilla.mozilla.org/show_bug.cgi?id=1010527), it's recommended to play the exported project using a Chromium-based browser instead of Firefox.

If you have any questions or suggestions for the PR let me know.

### CODE REVIEW

**Comment by DmitriySalnikov** [comment]
Awesome!

> And updating the version of emsdk to `3.1.46`

Ooh, I was slightly wrong with the version. 😅

(Looking at the screenshot, at first I thought that the colors were broken, and then I remembered that I had already reported this bug and it had already been fixed in version 4.2.)

Can you `squash` your changes?

```
git rebase -i 027970584ed171343dff55f37a211ed533b0f3ec
git push -f
```

However, I'm not sure if binaries are needed in this PR, but it's not that important.

---

It looks like everything is working as intended!

image

---

And since the changes were made in the patch, it seems to me that they should be duplicated in the `godot-cpp` itself.

**Comment by nicholas-maltbie** [comment]
Hey, happy to update the project and squash the commits.

> However, I'm not sure if binaries are needed in this PR, but it's not that important.

I can revert those changes if you would rather add them in a separate commit or PR. I mostly added them for testing.

I think I only added the wasm files so I can manually remove the other updates as well. 

If you have any other suggestions or comments let me know. 

> And since the changes were made in the patch, it seems to me that they should be duplicated in the godot-cpp itself.

Think it's a good idea to submit it to the `godot-cpp` repo? Do they have a protocol for contributing or can I open a pull request like here.

**Comment by DmitriySalnikov** [comment]
> Think it's a good idea to submit it to the `godot-cpp` repo? Do they have a protocol for contributing or can I open a pull request like here.

Why not? They have [recommendations](https://github.com/godotengine/godot-cpp#contributing) and you can just do a fork and PR.
I think you may be asked to expose the flag settings in the `options` method, because I do not know how specific they are for this project.
Only one limitation will be at the first PR, this is that CI/CD will not automatically start for you in their repository.

Otherwise, everything is fine. I was able to build locally and run.

Thanks!

**Comment by nicholas-maltbie** [comment]
Sounds good. thanks for reviewing the PR. I'll make a PR to the godot repo after reading over those recommendations. 

Oh, I'm also working on adding an automated github pages build for the project (upload the demo project to github pages for the repo). Would you be interested in adding that to this project as well?

**Comment by DmitriySalnikov** [comment]
Do you mean some kind of documentation generation or just auto-uploading and updating the demo project on github pages?

**Comment by nicholas-maltbie** [comment]
> Do you mean some kind of documentation generation or just auto-uploading and updating the demo project on github pages?

Auto generating the site and uploading to GitHub pages. I have it working in my repo right now here - https://nickmaltbie.com/godot_debug_draw_3d/

Auto generating documentation could be added as well but I always like including demos of my libraries that people can checkout from the github page. I want to include these demos for some godot projects I am working on and found your repo while researching.

**Pull request merged**
